version: "3"

services:
  # Shared container of the app that acts as a proxy.
  nginx:
    container_name: nginx
    build: ./nginx
    networks:
      - living-room-arcades
    ports:
      - 80:80
      