name: deploy
on:
  push:
    branches:
      - master

# Ensures that only one deploy task per branch/environment will run at a time
concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.KEY }}
          script: cd living-room-arcades && git fetch && git checkout ${{ github.ref_name }} && git pull && ./deploy.sh

      # Debug ${{ github }} object
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"
